---
title: "Wrangling Data"
author: "Patrick Burke"
date: "3/21/2022"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
##install.packages("janitor")
library(janitor)
```

## World record scraping

```{r}
url2 <- "https://mkwrs.com/mk8dx/wrs.php?date=0"
wr <- read_html(url2)
wr_tab <- wr %>% html_nodes("table")
```

```{r}
worldrecords <- wr_tab[[2]] %>% html_table()

worldrecords <- worldrecords %>%
  subset(select = (-c(4,11)))
```

## Found some new datasets. Possibly better?
```{r}
bodiesNew <- read_csv("bodies.csv")
bodiesNew <- bodiesNew %>%
  mutate(Karts = Body) %>%
  subset(select = (-c(2)))


tiresNew <- read_csv("tires.csv")
tiresNew <- tiresNew %>%
  mutate(Tires = Body) %>%
  subset(select = (-c(2)))

glidersNew <- read_csv("gliders.csv")
glidersNew <- glidersNew %>%
  mutate(Gliders = Body) %>%
  subset(select = (-c(2)))

charactersNew <- read_csv("characters.csv")


mkfullNew <- full_join(bodiesNew, charactersNew)
mkfullNew <-full_join(mkfullNew, glidersNew)
mkfullNew <- full_join(mkfullNew, tiresNew)
```

```{r}
selected <- mkfullNew %>% 
  filter(Character == "Mario" | Gliders == "Plane" 
             | Tires == "Azure Roller" | Karts == "Standard Kart")


finalstats = data.frame(value=apply(selected[2:13],2,sum))

finalstats <- finalstats %>%
  mutate(key = rownames(finalstats))

ggplot(data = finalstats, aes(x=value, y = key)) +
  geom_col(colour="yellow", fill = "gold")


#wrcombined <- right_join(worldrecords, mkfullNew)

```





